# -*- coding: utf-8 -*-
"""Copie de Exercice 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13c1MuFlgee1GLDKtbdm0mKe2v3Lrarla
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount("/content/drive")

"""ouverture du fichier"""

path_data = '/content/drive/MyDrive/Projet stats/covid19.xlsx'
data = pd.read_excel(path_data)
data.head()

"""convertion de la variable date en datetime"""

pd.to_datetime(data['date'])

"""suppression des lignes avec des valeurs manquantes"""

#data.isnull().sum()
data.drop(index =3, inplace=True)

"""taux de positivité"""

data["TP"] = (data["cas"] *100) / data["tests"]
data.head()

"""les cas cumullées"""

data["NC"] = data["cas"].cumsum()
data

"""representation de cas et tests en fontion de la date"""

plt.plot(data.date,data.tests)
plt.plot(data.date,data.cas)
plt.title('representation de cas et tests en fontion de la date')
plt.xlabel("date")
plt.ylabel("tests et cas")

"""representation de cas et tests en fontion de la date"""

plt.plot(data.date,data.tests)
plt.plot(data.date,data.cas)
plt.title('representation de cas et tests en fontion de la date')
plt.xlabel("date")
plt.ylabel("tests et cas")

"""representation de cas en boxplot et en histogramme"""

plt.figure(figsize=(12, 8))
plt.boxplot(data.cas)
plt.title('representation de cas en boxplot')

plt.figure(figsize=(12, 8))
plt.hist(data.cas)
plt.title('representation de cas en histogramme')

"""discrediter de la variable cas et la mettre dans cas_classe"""

def discret(s):
    if (s>=np.min(data['cas'])and s<=np.quantile(data['cas'],0.25)):
         return"A"
    elif (s>np.quantile(data['cas'],0.25)and s<=np.quantile(data['cas'],0.5)):
         return"B"
    elif (s>np.quantile(data['cas'],0.5)and s<=np.quantile(data['cas'],0.75)):
         return"C"
    else:
         return"D"

data['cas_classe']= data['cas'].apply(discret) 
#data.dtypes
#data.shape

data['cas_classe']= data['cas_classe'].astype('category')
data['cas_classe']

"""fréquence cas_classe"""

print(pd.value_counts(data['cas_classe']))
print(path_data)